### ISSUE TITLE
Format design tokens changelog to align with module template

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-design-system#95]
## **Description**

Update the CHANGELOG tag diff links in the `design-tokens` package to follow the MetaMask module template’s tag naming convention. This ensures that all future tag diffs are consistent with the naming scheme used in the monorepo and meet the `@metamask/` namespace requirements after migration.

## **Task Details**

1. **Navigate to the Package Directory**:
   - Navigate to `merged-packages/design-tokens` within the monorepo.

2. **Run the Validation Script**:
   - Execute the following command to validate and update tag diff links:
     ```bash
     ../../scripts/validate-changelog.sh @metamask/design-tokens
     ```
   - This command will apply the tag diff links based on the `@metamask/` namespace and the module template convention.

3. **Handle Renamed Packages (if applicable)**:
   - If the `design-tokens` package requires renaming with the `@metamask/` namespace, run the script with additional arguments:
     ```bash
     ../../scripts/validate-changelog.sh --version-before-package-rename --tag-prefix-before-package-rename
     ```

4. **Review and Apply Changes**:
   - Apply any diffs outputted by the script to the CHANGELOG.

For further instructions on the validation script, refer to the [validate-changelog documentation](https://github.com/MetaMask/auto-changelog#validate).

## **Acceptance Criteria**

- [ ] CHANGELOG tag diff links in `design-tokens` follow the format `@metamask/design-tokens@[version-number]`.
- [ ] All future tag links conform to the MetaMask module template’s naming scheme.
- [ ] If applicable, previous versions in the CHANGELOG are updated to reflect any renaming conventions.

## **References**

- MetaMask Package Migration Process Guide: **PR#7**.
- [validate-changelog documentation](https://github.com/MetaMask/auto-changelog#validate).
